version: '3'

services:
  container-mcp:
    image: container-mcp:latest
    container_name: container-mcp
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./volume/config:/app/config:ro
      - ./volume/data:/app/data:rw
      - ./volume/logs:/app/logs:rw
      - ./volume/sandbox:/app/sandbox:rw
      - ./volume/kb:/app/kb:rw
      - ./volume/temp:/app/temp:rw
    env_file:
      - ${CUSTOM_ENV_FILE:-config/app.env}
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    networks:
      - container-mcp-network

networks:
  container-mcp-network:
    name: container-mcp-network
    external: true 
